#!/bin/sh
# xrdb-to-alacritty
# Version 0.1

# Function to display error and quit
die() {
  printf "ERR: %s\n" "$1" >&2
  exit 1
}

DEFAULT_UNIX_CONFIG="$HOME/.config/alacritty/alacritty.toml"

# Get config file
if [ -n "$1" ]; then
  [ -e "$1" ] || die "Selected config doesn't exist, exiting script."
  printf "Config found, destination ready.\n"
  CFG=$1
else
  [ -e "$DEFAULT_UNIX_CONFIG" ] || die "Alacritty config not found, exiting script."
  printf "Using default config.\n"
  CFG="$DEFAULT_UNIX_CONFIG"
fi

# Create temp file for sed results
tempfile=$(mktemp)
trap 'rm $tempfile' INT TERM EXIT

# Delete existing color declarations generated by this script
# If begin comment exists
if grep -q '^# BEGIN XTA' "$CFG"; then
  # And if end comment exists
  if grep -q '^# END XTA' "$CFG"; then
    # Delete contents of the block
    printf "Existing generated colors found, replacing new colors...\n"
    sed '/^# BEGIN XTA/,/^# END XTA/ {
      /^# BEGIN XTA/! { /^# END XTA/!d; }
    }' "$CFG" > "$tempfile" \
      && cat "$tempfile" > "$CFG"
  # If no end comment, don't do anything
  else
    die "No '# END XTA' comment found, please ensure it is present."
  fi
# If no begin comment found
else
  # Don't do anything and notify user if there's an end comment in the file
  ! grep -q '^# END XTA' "$CFG" || die "Found '# END XTA' comment, but no '# BEGIN XTA' comment found. Please ensure it is present."
  printf "There's no existing 'generated' colors, adding comments...\n";
  printf '# BEGIN XTA\n# END XTA' >> "$CFG";
fi

# Write new color definitions
{ sed "/^# BEGIN XTA/ r /dev/stdin" "$CFG" > "$tempfile" <<EOF
[colors.primary]
background = "$(xrdb -query | grep "background" | cut -f 2 | head -1)"
foreground = "$(xrdb -query | grep "foreground" | cut -f 2 | head -1)"

[colors.normal]
black = "$(xrdb -query | grep "color0" | cut -f 2 | head -1)"
red = "$(xrdb -query | grep "color1" | cut -f 2 | head -1)"
green = "$(xrdb -query | grep "color2" | cut -f 2 | head -1)"
yellow = "$(xrdb -query | grep "color3" | cut -f 2 | head -1)"
blue = "$(xrdb -query | grep "color4" | cut -f 2 | head -1)"
magenta = "$(xrdb -query | grep "color5" | cut -f 2 | head -1)"
cyan = "$(xrdb -query | grep "color6" | cut -f 2 | head -1)"
white = "$(xrdb -query | grep "color7" | cut -f 2 | head -1)"

[colors.bright]
black = "$(xrdb -query | grep "color8" | cut -f 2 | head -1)"
red = "$(xrdb -query | grep "color9" | cut -f 2 | head -1)"
green = "$(xrdb -query | grep "color10" | cut -f 2 | head -1)"
yellow = "$(xrdb -query | grep "color11" | cut -f 2 | head -1)"
blue = "$(xrdb -query | grep "color12" | cut -f 2 | head -1)"
magenta = "$(xrdb -query | grep "color13" | cut -f 2 | head -1)"
cyan = "$(xrdb -query | grep "color14" | cut -f 2 | head -1)"
white = "$(xrdb -query | grep "color15" | cut -f 2 | head -1)"
EOF
} && cat "$tempfile" > "$CFG" \
  && rm "$tempfile"
trap - INT TERM EXIT
